### ISSUE TITLE
Figure out crash

### ISSUE THREAD

**Issue by VorpalBlade** [VorpalBlade/point_cloud_subsampler#1]
Not able to reproduce it.

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
[sensors/camera/camera_nodelet_manager-2] process has died [pid 11940, exit code -6, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/home/arvid/.ros/log/b28702
20-eaa5-11e9-8118-94c69112175a/sensors-camera-camera_nodelet_manager-2.log].
```

**Comment by VorpalBlade** [comment]
```
(gdb) bt
#0  0x00007ffff6156428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff615802a in __GI_abort () at abort.c:89
#2  0x00007ffff679084d in __gnu_cxx::__verbose_terminate_handler () at ../../../../src/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff678e6b6 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../src/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff678e701 in std::terminate () at ../../../../src/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff678e919 in __cxxabiv1::__cxa_throw (obj=obj@entry=0x644250, 
    tinfo=tinfo@entry=0x413c18 <typeinfo for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >>, 
    dest=dest@entry=0x40d520 <boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >::~clone_impl()>)
    at ../../../../src/libstdc++-v3/libsupc++/eh_throw.cc:87
#6  0x000000000040eff3 in boost::throw_exception<boost::lock_error> (e=...) at /usr/include/boost/throw_exception.hpp:69
#7  0x00007ffff7b8718f in boost::unique_lock<boost::mutex>::lock() () from /opt/ros/kinetic/lib/libtf2_ros.so
#8  0x00007ffff6ada611 in boost::unique_lock<boost::mutex>::unique_lock (m_=..., this=0x7fffffffbfc0) at /usr/include/boost/thread/lock_types.hpp:124
#9  message_filters::Signal1<sensor_msgs::PointCloud2_<std::allocator<void> > >::call (this=0x645af8, event=...) at /opt/ros/kinetic/include/message_filters/signal1.h:112
#10 0x00007ffff6ae6df9 in message_filters::SimpleFilter<sensor_msgs::PointCloud2_<std::allocator<void> > >::signalMessage (event=..., this=<optimized out>)
    at /opt/ros/kinetic/include/message_filters/simple_filter.h:136
#11 tf2_ros::MessageFilter<sensor_msgs::PointCloud2_<std::allocator<void> > >::CBQueueCallback::call (this=<optimized out>) at /opt/ros/kinetic/include/tf2_ros/message_filter.h:596
#12 0x00007ffff7646838 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) () from /opt/ros/kinetic/lib/libroscpp.so
#13 0x00007ffff764823b in ros::CallbackQueue::callAvailable(ros::WallDuration) () from /opt/ros/kinetic/lib/libroscpp.so
#14 0x00007ffff76a4e39 in ros::SingleThreadedSpinner::spin(ros::CallbackQueue*) () from /opt/ros/kinetic/lib/libroscpp.so
#15 0x00007ffff7689e9b in ros::spin() () from /opt/ros/kinetic/lib/libroscpp.so
#16 0x000000000040a683 in main (argc=1, argv=0x7fffffffd688) at /home/arvid/ipw/ws/src/sensors/point_cloud_subsampler/src/point_cloud_subsampler/node.cpp:28
```
